//! CLI parsing + resolved `Config`.
use std::fs;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;

/// `yt-downloader-webui` -- a single-binary web wrapper around `yt-dlp`.
#[derive(Parser, Debug)]
#[command(name = "yt-downloader-webui", version, about)]
pub struct Cli {
    /// Where yt-dlp writes files (passed as -P). Default: ~/Downloads
    #[arg(short, long, value_name = "DIR")]
    pub download_dir: Option<String>,

    /// Browser to pull cookies from via --cookies-from-browser (matches the
    /// yt-dlp flag). Optional; nothing is forwarded to yt-dlp unless set --
    /// omit to run without cookies.
    #[arg(short = 'b', long = "cookies-from-browser", value_name = "BROWSER")]
    pub cookies_from_browser: Option<String>,

    /// Path to yt-dlp binary. Default: yt-dlp (PATH).
    #[arg(long, value_name = "PATH", default_value = "yt-dlp")]
    pub yt_dlp: String,

    /// Path to ffmpeg binary, used to generate a thumbnail from a downloaded
    /// file when the probe found none. Default: ffmpeg (PATH).
    #[arg(long, value_name = "PATH", default_value = "ffmpeg")]
    pub ffmpeg: String,

    /// Path to ffprobe binary, used to identify video files during import and
    /// extract codec/resolution/bitrate/duration metadata for the item details
    /// page. Default: ffprobe (PATH). Should ship alongside ffmpeg.
    #[arg(long, value_name = "PATH", default_value = "ffprobe")]
    pub ffprobe: String,

    /// Queue persistence directory (one JSON file per item). Default:
    /// ~/.local/share/yt-downloader-webui/queue/
    #[arg(long, value_name = "DIR")]
    pub state_dir: Option<String>,

    /// Thumbnail cache directory. Default: ~/.cache/yt-downloader-webui/thumbs/
    /// Thumbnails are fetched during the yt-dlp probe (or generated by ffmpeg
    /// after a download) and cached here, keyed by sha1 of their source. The
    /// directory is a cache -- safe to clear; contents are re-fetched /
    /// re-generated as needed.
    #[arg(long, value_name = "DIR")]
    pub cache_dir: Option<String>,

    /// Bind address (host:port). Default: 127.0.0.1:8080 (loopback). Use
    /// 0.0.0.0:<port> to listen on all interfaces -- DANGEROUS; prints a warning.
    #[arg(long, value_name = "ADDR", default_value = "127.0.0.1:8080")]
    pub bind: String,

    /// Sleep between consecutive downloads (seconds) to avoid hammering the
    /// source. Set to 0 to disable. Default: 20.
    #[arg(long, value_name = "SECONDS", default_value_t = 20)]
    pub sleep: u64,

    /// Verbose server logs (yt_downloader_webui=debug).
    #[arg(short, long)]
    pub verbose: bool,

    /// Shut the server down after N seconds. Intended for testing so the
    /// binary self-terminates without an external kill; unset by default.
    #[arg(long, value_name = "SECONDS")]
    pub timeout: Option<u64>,
}

/// Resolved runtime configuration.
#[derive(Clone, Debug)]
pub struct Config {
    pub download_dir: PathBuf,
    pub cookies_from_browser: Option<String>,
    pub yt_dlp: String,
    /// Path to ffmpeg (thumbnail generation fallback). Default: ffmpeg.
    pub ffmpeg: String,
    /// Path to ffprobe (media metadata + video identification for import).
    pub ffprobe: String,
    pub state_dir: PathBuf,
    /// Thumbnail cache dir (XDG cache home by default). Thumbnails are fetched
    /// during the probe or generated by ffmpeg after a download; safe to clear.
    pub cache_dir: PathBuf,
    pub addr: SocketAddr,
    pub timeout: Option<u64>,
    /// Sleep between consecutive downloads (rate-limit). 0 disables.
    pub sleep: Duration,
}

impl Cli {
    /// Resolve CLI args into a `Config`, expanding `~`, creating directories,
    /// and validating the listen address.
    pub fn into_config(self) -> Result<Config> {
        let home = home_dir().context("could not determine home directory")?;

        let download_dir = match self.download_dir {
            Some(d) => expand_tilde(&d, &home),
            None => home.join("Downloads"),
        };
        fs::create_dir_all(&download_dir).with_context(|| {
            format!("failed to create download dir: {}", download_dir.display())
        })?;

        // Optional: forward the browser name to yt-dlp only when explicitly set.
        // Omit the flag entirely to run without cookies.
        let cookies_from_browser = self.cookies_from_browser;

        let state_dir = match self.state_dir {
            Some(s) => expand_tilde(&s, &home),
            None => home
                .join(".local")
                .join("share")
                .join("yt-downloader-webui")
                .join("queue"),
        };
        fs::create_dir_all(&state_dir)
            .with_context(|| format!("failed to create state dir: {}", state_dir.display()))?;

        let cache_dir = match self.cache_dir {
            Some(c) => expand_tilde(&c, &home),
            None => home
                .join(".cache")
                .join("yt-downloader-webui")
                .join("thumbs"),
        };
        fs::create_dir_all(&cache_dir)
            .with_context(|| format!("failed to create cache dir: {}", cache_dir.display()))?;

        let addr: SocketAddr = self
            .bind
            .parse()
            .with_context(|| format!("invalid bind address: {}", self.bind))?;

        // Loud warning when binding anything other than loopback. Printed to
        // stderr so it's visible even if the tracing subscriber failed to init;
        // also emitted via tracing so it lands in journald with a WARN priority.
        if !addr.ip().is_loopback() {
            eprintln!(
                "WARNING: --bind {bind} listens on a non-loopback interface. Anyone who can \
                 reach this machine can run yt-dlp with your browser cookies, download any \
                 file in {dir}, and delete files. Do not expose to untrusted networks.",
                bind = self.bind,
                dir = download_dir.display(),
            );
            tracing::warn!(
                bind = %self.bind,
                "listening on a non-loopback interface; anyone reachable can run yt-dlp with your cookies, read/delete files in the download dir"
            );
        }

        Ok(Config {
            download_dir,
            cookies_from_browser,
            yt_dlp: self.yt_dlp,
            ffmpeg: self.ffmpeg,
            ffprobe: self.ffprobe,
            state_dir,
            cache_dir,
            addr,
            timeout: self.timeout,
            sleep: Duration::from_secs(self.sleep),
        })
    }
}

/// Resolve a home directory, preferring `$HOME`, falling back to the `dirs` crate.
pub fn home_dir() -> Option<PathBuf> {
    if let Some(h) = std::env::var_os("HOME")
        && !h.is_empty()
    {
        return Some(PathBuf::from(h));
    }
    dirs::home_dir()
}

/// Expand a leading `~` to `home`.
fn expand_tilde(input: &str, home: &Path) -> PathBuf {
    if input == "~" {
        return home.to_path_buf();
    }
    if let Some(rest) = input.strip_prefix("~/") {
        return home.join(rest);
    }
    PathBuf::from(input)
}

use anyhow::{Context, Result, bail};
use clap::Parser;

/// Quick helper used by `main` to validate the yt-dlp binary is callable.
pub fn yt_dlp_check(yt_dlp: &str) -> Result<()> {
    let out = std::process::Command::new(yt_dlp).arg("--version").output();
    match out {
        Ok(o) if o.status.success() => Ok(()),
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            bail!("`{yt_dlp} --version` exited non-zero: {stderr}");
        }
        Err(e) => {
            bail!(
                "could not run `{yt_dlp} --version`: {e}.\n\
                 Install yt-dlp or pass --yt-dlp <path>."
            );
        }
    }
}

/// Soft check that ffmpeg is callable (used to generate thumbnails). Returns
/// `Ok(())` if reachable, `Err(...)` otherwise; `main` only warns on failure
/// (thumbnail generation is best-effort, so a missing ffmpeg is not fatal).
pub fn ffmpeg_check(ffmpeg: &str) -> Result<()> {
    let out = std::process::Command::new(ffmpeg).arg("-version").output();
    match out {
        Ok(o) if o.status.success() => Ok(()),
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            bail!("`{ffmpeg} -version` exited non-zero: {stderr}");
        }
        Err(e) => {
            bail!(
                "could not run `{ffmpeg} -version`: {e}.\n\
                 Install ffmpeg or pass --ffmpeg <path>; thumbnail generation will be skipped."
            );
        }
    }
}

/// Soft check that ffprobe is callable (used to identify videos + extract
/// metadata during import). Returns `Ok(())` if reachable, `Err(...)`
/// otherwise; `main` only warns on failure (import is best-effort, so a
/// missing ffprobe just disables import rather than being fatal).
pub fn ffprobe_check(ffprobe: &str) -> Result<()> {
    let out = std::process::Command::new(ffprobe).arg("-version").output();
    match out {
        Ok(o) if o.status.success() => Ok(()),
        Ok(o) => {
            let stderr = String::from_utf8_lossy(&o.stderr);
            bail!("`{ffprobe} -version` exited non-zero: {stderr}");
        }
        Err(e) => {
            bail!(
                "could not run `{ffprobe} -version`: {e}.\n\
                 Install ffmpeg (which ships ffprobe) or pass --ffprobe <path>; \
                 media import/metadata will be skipped."
            );
        }
    }
}
